#!/usr/bin/env python3
"""Emit tab_atoms_structure.tex: where the reward lives, for all three architectures.

Quetzal's atoms-versus-coordinates ablation asks whether the reward is carried by the atom
types a guide can edit or by the channel it cannot touch. MolGPT and G2PT have no coordinate
channel, so the analogous question is atoms versus the structural tokens: bond, ring-closure
and branch characters for MolGPT, edge tokens for G2PT.

The two columns are not the same statistic and the table says so. T1 is a mean absolute
reward change under a forced intervention. T2 is a mean per-molecule standard deviation
under repeated re-rolls of the other channel. What makes them comparable is the question:
each is the reward movement attributable to one channel, on the same molecules and the same
log-reward scale.

Reads the per-leg JSON the diagnostics write. No GPU.

    python scripts/make_atoms_vs_structure_table.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))
OUT = os.path.join(REPO, "papers", "current", "src", "tab_atoms_structure.tex")

REWARD_TITLE = {"osim": "Osimertinib", "peri": "Perindopril",
                "fexo": "Fexofenadine", "nitrogen": "Nitrogen"}
ORDER = ["osim", "peri", "fexo", "nitrogen"]


def quetzal_row():
    p = os.path.join(REPO, "results", "ablations", "atoms-vs-coords", "atoms_vs_coords.json")
    if not os.path.exists(p):
        return []
    d = json.load(open(p))
    t1, t2 = d["T1_atom_sensitivity"], d["T2_coord_sensitivity"]
    return [{
        "leg": "Quetzal", "channel": "coordinates", "reward": "osim",
        "t1": t1["mean_abs_reward_change"], "t2": t2["coord_only_reward_std_mean"],
        "parse": None,
    }]


def pilot_rows(leg, title, channel):
    rows = []
    for r in ORDER:
        p = os.path.join(REPO, leg, "results", "ablations", "atoms-vs-structure",
                         "%s_%s.json" % (leg, r))
        if not os.path.exists(p):
            continue
        d = json.load(open(p))
        t1, t2 = d["T1_atom_sensitivity"], d["T2_structure_sensitivity"]
        rows.append({
            "leg": title, "channel": channel, "reward": r,
            "t1": t1["mean_abs_change"], "t2": t2["mean_std_from_structure"],
            "parse": t2["reroll_valid_frac"],
        })
    return rows


def main():
    rows = quetzal_row()
    rows += pilot_rows("molgpt", "MolGPT", "structural tokens")
    rows += pilot_rows("g2pt", "G2PT", "edge tokens")
    if not rows:
        raise SystemExit("no ablation output found")

    L = []
    L.append("% generated by scripts/make_atoms_vs_structure_table.py -- do not edit by hand")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption[Where the reward lives, all three architectures]{\textbf{On every "
             r"architecture and every objective, the channel a guide can edit moves the reward "
             r"further than the channel it cannot.} Reward movement attributable to each "
             r"channel, on frozen-prior molecules with no further training. \emph{Atom} forces "
             r"every atom decision to the guide's own top-1 choice and reports the mean "
             r"absolute change in log reward. \emph{Other channel} holds the realised atoms "
             r"fixed, re-rolls the other channel five times and reports the mean per-molecule "
             r"standard deviation. That other channel is the coordinate diffusion for Quetzal, "
             r"the bond, ring-closure and branch tokens for MolGPT and the edge tokens for "
             r"G2PT. The final column is the fraction of re-rolls that still parse, which is "
             r"undefined for Quetzal because a re-rolled geometry always yields a molecule.}")
    L.append(r"\label{tab:atoms-structure}")
    L.append(r"\begin{tabular}{llrrrr}")
    L.append(r"\toprule")
    L.append(r"Model & Objective & Atom & Other channel & Ratio & Re-roll parse \\")
    L.append(r"\midrule")

    last = None
    for r in rows:
        if last is not None and r["leg"] != last:
            L.append(r"\midrule")
        last = r["leg"]
        ratio = r["t1"] / r["t2"] if r["t2"] else float("nan")
        parse = "--" if r["parse"] is None else "%.3f" % r["parse"]
        L.append("%s & %s & %.3f & %.3f & %.1f & %s \\\\"
                 % (r["leg"], REWARD_TITLE[r["reward"]], r["t1"], r["t2"], ratio, parse))

    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", os.path.relpath(OUT, REPO))
    for r in rows:
        print("  %-8s %-10s atom=%.3f other=%.3f ratio=%.1f"
              % (r["leg"], r["reward"], r["t1"], r["t2"], r["t1"] / r["t2"]))


if __name__ == "__main__":
    main()
